creation_rules:
  - path_regex: (secrets[/\\]|^)[^/\\]*\.sops\.ya?ml$
    age: age177sk4cealkrtkf64xx5p7vtxjw9fchjkgwvfeztrfg02ledn9veqr3vfpq,age1mhmv9sqqrwdr6d5yx8trmjlu82wuuevcd6at83xmauhsg4s2242qgpeegz
