"""LLM routing chain — ordered fallback across providers.

The default chain is ``groq → openai → ollama → stub``. The fine-tuned GGUF
(``llama_cpp``) is deliberately excluded: it was trained on a different prompt
format and, on the production prompt, emits annotation echo and base-model
leakage instead of verse (see ``scripts/benchmark_metre.py``). Register this
client as ``route`` in ``registry`` so ``poesia write`` uses the chain by
default. The router sticks to the first provider that serves a request and
falls back on any failure (missing key, 401/429, model-not-found, unreachable
local service).
"""

from __future__ import annotations

import os
from typing import Any

from poesia.generation.llm_client import GROQ_MODEL

# Ordered fallback chain. ``model`` is a per-provider override; omitted means
# "use that provider's own default". This is the single source of truth for
# routing — not a hardcoded default scattered across registry/llm_client.
DEFAULT_ROUTE: list[dict[str, Any]] = [
    {"provider": "groq", "model": GROQ_MODEL},  # hosted general model (primary)
    {"provider": "openai"},  # default gpt-4o-mini (OPENAI_API_KEY)
    {"provider": "ollama"},  # local model (OLLAMA_HOST / gemma2:2b)
    {"provider": "stub"},  # deterministic offline floor
]


def _route_from_env() -> list[dict[str, Any]] | None:
    """Parse LLM_ROUTE (compact: provider[:model],provider[:model],...)."""
    raw = os.environ.get("LLM_ROUTE")
    if not raw:
        return None
    route: list[dict[str, Any]] = []
    for item in raw.split(","):
        item = item.strip()
        if not item:
            continue
        if ":" in item:
            provider, model = item.split(":", 1)
            route.append({"provider": provider.strip(), "model": model.strip()})
        else:
            route.append({"provider": item})
    return route


def default_route_for(
    form: str | None = None,
    language: str | None = None,
) -> list[dict[str, Any]]:
    """Default route — currently form-agnostic.

    ``form``/``language`` are accepted (and already threaded through from the
    CLI) so routing can become form-aware again once the fine-tuned GGUF is
    re-trained against the production prompt and re-proven by the benchmark.
    Until then every form is served by the hosted chain in ``DEFAULT_ROUTE``.
    """
    return DEFAULT_ROUTE


class RoutedLLMClient:
    """LLMClient that routes across providers, sticking to the first that works.

    Clients are instantiated once and cached; the first provider that serves a
    request becomes the active one and is reused for subsequent calls, so a
    whole poem is generated by a single model. On failure the router demotes the
    active provider and re-walks the chain.
    """

    def __init__(
        self,
        route: list[dict[str, Any]] | None = None,
        form: str | None = None,
        language: str | None = None,
    ) -> None:
        self._route = route or _route_from_env() or default_route_for(form=form, language=language)
        self._clients: list[tuple[str, Any]] = []
        self._active: tuple[str, Any] | None = None
        self.provider = "route"
        self.model = None

    def _all_clients(self) -> list[tuple[str, Any]]:
        """Lazily instantiate + cache every route entry exactly once."""
        if not self._clients:
            # Lazy import to avoid a circular import with registry.py.
            from poesia.generation.registry import get_llm

            for entry in self._route:
                name = entry["provider"]
                overrides = {k: v for k, v in entry.items() if k != "provider"}
                try:
                    self._clients.append((name, get_llm(name, **overrides)))
                except Exception:  # noqa: BLE001 — provider unavailable, skip
                    continue
        return self._clients

    def _record(self, client: Any, name: str) -> None:
        """Expose the actual provider/model used, for CLI logging."""
        self.model = getattr(client, "model", None)
        self.provider = getattr(client, "provider", None) or name

    def generate(self, prompt: str, n: int = 1, temperature: float = 0.9) -> list[str]:
        last_error: Exception | None = None

        # Stick to the provider that already worked, so a whole poem uses one
        # model; demote it and re-walk the chain only if it fails.
        if self._active is not None:
            name, client = self._active
            try:
                result = client.generate(prompt, n=n, temperature=temperature)
                self._record(client, name)
                return result
            except Exception as exc:  # noqa: BLE001 — active failed, re-walk
                last_error = exc
                self._active = None

        for name, client in self._all_clients():
            try:
                result = client.generate(prompt, n=n, temperature=temperature)
            except Exception as exc:  # noqa: BLE001 — fall back to next provider
                last_error = exc
                continue
            self._active = (name, client)
            self._record(client, name)
            return result

        if last_error is not None:
            raise last_error
        raise RuntimeError("LLM route exhausted — no usable provider")

    def repair(self, line: str, defect_description: str) -> str:
        last_error: Exception | None = None

        if self._active is not None:
            name, client = self._active
            repair = getattr(client, "repair", None)
            if repair is not None:
                try:
                    result = repair(line, defect_description)
                    self._record(client, name)
                    return result
                except Exception as exc:  # noqa: BLE001 — active failed, re-walk
                    last_error = exc
                    self._active = None

        for name, client in self._all_clients():
            repair = getattr(client, "repair", None)
            if repair is None:
                continue
            try:
                result = repair(line, defect_description)
            except Exception as exc:  # noqa: BLE001 — fall back to next provider
                last_error = exc
                continue
            self._active = (name, client)
            self._record(client, name)
            return result

        if last_error is not None:
            raise last_error
        raise RuntimeError("LLM route exhausted — no usable provider (repair)")
